### ISSUE TITLE
Throws errors even for the test files.

### ISSUE THREAD

**Issue by wgaylord** [yuanmie/KCC#1]
I will post the error message when I can. (Just remembered about it and I am away from my comp)
But the test files throw errors when trying to compile them.

**Comment by yuanmie** [comment]
I am so sorry. It's  a incomplete project and mostly base on cbc. I am developing and not check all test file and not fix all bug. I'll fix it as fast as i can. Thank you so much.

**Comment by yuanmie** [comment]
The test file "heart.c" is ok. I'll write how to install kcc on ubunut later.Thank you  again.
